name: zizmor

on:
  push:
    branches: [main]
  pull_request:
  merge_group:

permissions: {}

concurrency:
  group: zizmor-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  audit:
    name: zizmor
    runs-on: ubuntu-latest
    permissions:
      contents: read # checkout
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Audit workflows (fail on findings)
        uses: zizmorcore/zizmor-action@cc914d7f3750a2d13d75c7f184a1060aa0e9d482 # v0.6.4
        with:
          version: 1.30.1
          min-severity: low
          advanced-security: false
          annotations: true

  code-scanning:
    name: zizmor (code scanning)
    if: github.event_name != 'merge_group'
    runs-on: ubuntu-latest
    permissions:
      contents: read # checkout
      security-events: write # upload SARIF to code scanning
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Audit workflows (SARIF upload)
        uses: zizmorcore/zizmor-action@cc914d7f3750a2d13d75c7f184a1060aa0e9d482 # v0.6.4
        with:
          version: 1.30.1
          advanced-security: true
